-- MySQL Script generated by MySQL Workbench
-- Fri Mar 25 09:57:01 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema urenregristratie
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema urenregristratie
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `urenregristratie` DEFAULT CHARACTER SET utf8 ;
USE `urenregristratie` ;

-- -----------------------------------------------------
-- Table `urenregristratie`.`Medewerker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `urenregristratie`.`Medewerker` (
  `ID_worker` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NULL,
  `Name` VARCHAR(45) NULL,
  `Last_Name` VARCHAR(45) NULL,
  `Level` INT(1) ZEROFILL NULL,
  PRIMARY KEY (`ID_worker`),
  UNIQUE INDEX `ID_medewerker_UNIQUE` (`ID_worker` ASC));
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `urenregristratie`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `urenregristratie`.`project` (
  ` ID_project` INT NOT NULL AUTO_INCREMENT,
  `Project_Naam` VARCHAR(45) NULL,
  `Project_start` DATE NULL,
  `Project_deadline` DATE NULL,
  PRIMARY KEY (` ID_project`),
  UNIQUE INDEX ` ID_project_UNIQUE` (` ID_project` ASC));
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `urenregristratie`.`activiteit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `urenregristratie`.`activiteit` (
  `ID_activity` INT NOT NULL AUTO_INCREMENT,
  `activity` VARCHAR(45) NOT NULL,
  `Done` INT ZEROFILL NULL,
  `Activity_date` DATE NOT NULL,
  `project_ ID_project` INT NOT NULL,
  PRIMARY KEY (`ID_activity`, `project_ ID_project`),
  UNIQUE INDEX `idactiviteit_UNIQUE` (`ID_activity` ASC));
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `urenregristratie`.`Medewerker_has_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `urenregristratie`.`Medewerker_has_project` (
  `Medewerker_ID_worker` INT NOT NULL,
  `project_ ID_project` INT NOT NULL,
  PRIMARY KEY (`Medewerker_ID_worker`, `project_ ID_project`));
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `urenregristratie`.`Medewerker_has_activiteit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `urenregristratie`.`Medewerker_has_activiteit` (
  `Medewerker_ID_worker` INT NOT NULL,
  `activiteit_ID_activity` INT NOT NULL,
  PRIMARY KEY (`Medewerker_ID_worker`, `activiteit_ID_activity`));
-- ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
